CREATE TABLE `contacts` (
    `id` INT(11) NOT NULL AUTO_INCREMENT,
    `fname` VARCHAR(20) NOT NULL,
    `lname` VARCHAR(20) NOT NULL,
    `email` VARCHAR(30) NOT NULL,
    `age` INT(3) NULL,
    `url` VARCHAR(50) NULL,
    PRIMARY KEY (`id`)
)  ENGINE=MYISAM AUTO_INCREMENT=2 DEFAULT CHARSET=LATIN1;
